AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation Template for creating the Lambda functions for crowdhandler.
  This template deploys three functions using code stored in S3:
    - crowdhandler-viewerRequest (from viewerRequest.zip)
    - crowdhandler-viewerResponse (from viewerResponse.zip)
    - crowdhandler-originOverride (from originOverride.zip)
  It publishes a version of the viewerRequest function for Lambda@Edge.
  A parameter for the CloudFront distribution is provided for user input.

Parameters:
  BucketName:
    Type: String
    Description: "The S3 bucket that contains the Lambda code packages."
    Default: "cloudfront-integration-bundles"
  ViewerRequestZipS3Key:
    Type: String
    Description: "The S3 key (path) for the viewerRequest.zip file within the bucket."
  ViewerResponseZipS3Key:
    Type: String
    Description: "The S3 key (path) for the viewerResponse.zip file within the bucket."
  OriginOverrideZipS3Key:
    Type: String
    Description: "The S3 key (path) for the originOverride.zip file within the bucket."
  CloudFrontDistribution:
    Type: String
    Description: "The CloudFront distribution name that these functions are associated with."

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: crowdhandler
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: logs:CreateLogGroup
                Resource: "arn:aws:logs:*:*:*"
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:log-group:*:*"

  CrowdhandlerViewerRequestLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: crowdhandler-viewerRequest
      Runtime: nodejs20.x
      Role: !GetAtt LambdaExecutionRole.Arn
      Handler: handlerViewerRequest.viewerRequest
      Code:
        S3Bucket: !Ref BucketName
        S3Key: !Ref ViewerRequestZipS3Key
      MemorySize: 128
      Timeout: 30

  CrowdhandlerViewerResponseLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: crowdhandler-viewerResponse
      Runtime: nodejs20.x
      Role: !GetAtt LambdaExecutionRole.Arn
      Handler: handlerViewerResponse.viewerResponse
      Code:
        S3Bucket: !Ref BucketName
        S3Key: !Ref ViewerResponseZipS3Key
      MemorySize: 128
      Timeout: 30

  CrowdhandlerOriginOverrideLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: crowdhandler-originOverride
      Runtime: nodejs20.x
      Role: !GetAtt LambdaExecutionRole.Arn
      Handler: handlerOriginOverride.originOverride
      Code:
        S3Bucket: !Ref BucketName
        S3Key: !Ref OriginOverrideZipS3Key
      MemorySize: 128
      Timeout: 30

  # Publish a version of the viewerRequest Lambda for Lambda@Edge associations.
  CrowdhandlerViewerRequestLambdaVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref CrowdhandlerViewerRequestLambda

Outputs:
  ViewerRequestLambdaVersionARN:
    Description: "The ARN of the published version of the crowdhandler-viewerRequest function."
    Value: !GetAtt CrowdhandlerViewerRequestLambdaVersion.Version
